# netlify.toml at the root of your Git repository
plugins = []
headers = []
redirects = []

# Build settings for your main static site (your React app's build output)
[build]
  # 'base' tells Netlify to change into this directory before running build commands.
  # This path is RELATIVE to your Git repository root.
  base = "server"

  # 'command' is the script Netlify runs to build your static site AND prepare functions.
  # This command will be executed from within the 'server' directory.
  command = "npm install && npm run build"

  # 'publish' is the directory containing the static files that Netlify should serve.
  # This path is RELATIVE to the 'base' directory (i.e., relative to 'server/').
  # **YOU MUST CONFIRM THIS PATH**:
  # - If your React build outputs to `server/public`, then use `public`.
  # - If your React build outputs to `server/dist`, then use `dist`.
  # - If your React build outputs to `server/build`, then use `build`.
  publish = "public" # <--- IMPORTANT: Adjust this based on your React build output folder name within 'server/'

# Netlify Functions configuration
[functions]
  # 'directory' specifies the folder where your Netlify Functions source code is located.
  # This path is RELATIVE to your 'base' directory ('server/').
  directory = "functions" # This means your functions are in 'your-project-root/server/functions'

# Example of function settings (optional)
# [functions."*"]
#   node_bundler = "esbuild"